def draw(reload, riceClass,playerClass,screen,growCount,playerImg,selectImg,selectPos,verTextOutline,verText,posTextOutline,posText,invTextOutline,invText):
    # 드로우
    reload(screen)
    for i in range(len(riceClass)):
        riceClass[i].draw()
        riceClass[i].grow(growCount)
    playerClass.draw(playerImg)
    screen.blit(selectImg[0], selectPos)
    screen.blit(verTextOutline, (10+2, 10))
    screen.blit(verTextOutline, (10-2, 10))
    screen.blit(verTextOutline, (10, 10+2))
    screen.blit(verTextOutline, (10, 10-2))
    screen.blit(verText, (10, 10))
    screen.blit(posTextOutline, (850+2, 10))
    screen.blit(posTextOutline, (850-2, 10))
    screen.blit(posTextOutline, (850, 10+2))
    screen.blit(posTextOutline, (850, 10-2))
    screen.blit(posText, (850, 10))
    screen.blit(invTextOutline, (10+2, 35))
    screen.blit(invTextOutline, (10-2, 35))
    screen.blit(invTextOutline, (10, 35+2))
    screen.blit(invTextOutline, (10, 35-2))
    screen.blit(invText, (10, 35))